# Generated by Django 5.1.4 on 2025-01-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='pages/images/avatars/06.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
